/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClosingBulanan.java
 *
 * Created on 31 Agu 12, 20:31:03
 */
package paperman.transaksi;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import paperman.Main;
import paperman.TextComponentUtils;
import paperman.model.codeGenerator;
import paperman.model.komposisiSetoran;

/**
 *
 * @author Nurul Chusna
 */
public class InputBonusBulanan extends javax.swing.JInternalFrame {

    /** Creates new form ClosingBulanan */
    private static InputBonusBulanan formBonusBulanan;
    private BigDecimal angsuran = BigDecimal.ZERO;
    private BigDecimal tabungan = BigDecimal.ZERO;
    private SimpleDateFormat dateFormatter = new SimpleDateFormat("ddMMyyyy");
    private komposisiSetoran komposisi;
    private codeGenerator genCode;
    private List<komposisiSetoran> listKomposisi = new ArrayList<komposisiSetoran>();
    private List<komposisiSetoran> listKomposisiBonus = new ArrayList<komposisiSetoran>();
    private final String[] item = new String[Main.getSistemService().komposisiRecord().size()];

    public static void inisialisasi() {
        formBonusBulanan = new InputBonusBulanan();
    }

    public static void destroy() {
        formBonusBulanan.dispose();
        formBonusBulanan = null;
        System.gc();
    }

    public static InputBonusBulanan getFormInputBonusBulanan() {
        return formBonusBulanan;
    }

    public InputBonusBulanan() {
        initComponents();
        TextComponentUtils.setCurrency(txtAngsuran);
        TextComponentUtils.setCurrency(txtTabungan);
//        LoadData();
        listKomposisi = Main.getSistemService().komposisiRecord();
        for (int i = 0; i < listKomposisi.size(); i++) {
            item[i] = listKomposisi.get(i).getNamaKomposisi();
        }
        cmbJenisArmada.setModel(new DefaultComboBoxModel(item));
    }

    private void setBonusBulanan() {
        if (komposisi == null) {
            komposisi = new komposisiSetoran();
        }
        genCode = Main.getSistemService().findBySpecific("SETORAN", cmbJenisArmada.getSelectedItem().toString());
        komposisi.setGenCodeRef(genCode);
        komposisi.setNamaKomposisi(cmbJenisArmada.getSelectedItem().toString() + "BONUS BULANAN");
        komposisi.setAngsuran(TextComponentUtils.parseNumberToBigDecimal(txtAngsuran.getText()));
        komposisi.setTabungan(TextComponentUtils.parseNumberToBigDecimal(txtTabungan.getText()));
    }

//    private void LoadData() {
//        listKomposisiBonus = Main.getSistemService().findBonusBulanan();
//        if(cmbJenisArmada.getSelectedIndex() == 0) {
//            if(!listKomposisiBonus.isEmpty()) {
//                txtAngsuran.setText(TextComponentUtils.formatNumber(listKomposisiBonus.get()));
//            }
//        }else if(cmbJenisArmada.getSelectedIndex == 1) {
//
//        }
//        if (komposisi != null) {
//            txtAngsuran.setText(TextComponentUtils.formatNumber(komposisi.getAngsuran()));
//            txtTabungan.setText(TextComponentUtils.formatNumber(komposisi.getTabungan()));
//        } else {
//            txtAngsuran.setText("0");
//            txtTabungan.setText("0");
//            txtAngsuran.requestFocus();
//        }
//    }
//
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        txtAngsuran = new javax.swing.JTextField();
        txtTabungan = new javax.swing.JTextField();
        mTitleButton1 = new id.web.martinusadyh.panel.MTitleButton();
        jLabel4 = new javax.swing.JLabel();
        cmbJenisArmada = new javax.swing.JComboBox();

        jLabel2.setText("jLabel2");

        setClosable(true);
        setTitle("Pengaturan Saldo Bonus Bulanan");

        jLabel1.setText("Saldo Bonus Angsuran");

        jLabel3.setText("Saldo Bonus Tabungan");

        btnProses.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnProses.setText("PROSES");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        mTitleButton1.setBorder(null);
        mTitleButton1.setFontTitle(new java.awt.Font("Tahoma", 1, 12));
        mTitleButton1.setIconHelpVisible(false);
        mTitleButton1.setTextTitlePanel("Input Saldo Komposisi Bonus Akhir Bulan");

        jLabel4.setText("Jenis Armada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbJenisArmada, 0, 170, Short.MAX_VALUE)
                    .addComponent(txtAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTabungan, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProses, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(334, Short.MAX_VALUE))
            .addComponent(mTitleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbJenisArmada, txtAngsuran, txtTabungan});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mTitleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbJenisArmada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAngsuran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTabungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        if (!txtAngsuran.getText().isEmpty() || !txtAngsuran.getText().equalsIgnoreCase("0") && !txtTabungan.getText().isEmpty() || !txtTabungan.getText().equalsIgnoreCase("0")) {
            setBonusBulanan();
            Main.getSistemService().save(komposisi);
            JOptionPane.showMessageDialog(this, "Setting Bonus Bulanan Berhasil Di Lakukan", "Pesan Sistem", JOptionPane.INFORMATION_MESSAGE);
            destroy();
        } else {
            JOptionPane.showMessageDialog(this, "Setting Bonus Bulanan Tidak Dapat Di Lakukan\nPeriksa Lagi Pengisian Data", "Pesan Sistem", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnProsesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox cmbJenisArmada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private id.web.martinusadyh.panel.MTitleButton mTitleButton1;
    private javax.swing.JTextField txtAngsuran;
    private javax.swing.JTextField txtTabungan;
    // End of variables declaration//GEN-END:variables
}
