/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManajemenPiutang.java
 *
 * Created on 01 Sep 12, 7:09:26
 */
package paperman.transaksi;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.joda.time.DateTime;
import paperman.Main;
import paperman.OsUtils;
import paperman.dialog.createNotesDialog;
import paperman.model.TransaksiStatus;
import paperman.model.closingBulanan;
import paperman.model.isClosedFor;
import paperman.model.setoran;
import paperman.model.setoranDetail;
import paperman.tablemodel.PiutangTableModel;

/**
 *
 * @author Nurul Chusna
 */
public class ManajemenPiutang extends javax.swing.JInternalFrame {

    public static ManajemenPiutang manajemenPiutang;
    private List<setoran> listSto;
    private List<setoranDetail> listStoDet = new ArrayList<setoranDetail>();
    private List<setoran> listHutang = new ArrayList<setoran>();
    private setoran sto;
    private setoranDetail sd;
    private JPopupMenu popupMenuContext;
    private Rectangle cellScopes;

    public static void inisialisasi() {
        manajemenPiutang = new ManajemenPiutang();
    }

    public static void destroy() {
        manajemenPiutang.dispose();
        manajemenPiutang = null;
    }

    public static ManajemenPiutang getManajemenPiutang() {
        return manajemenPiutang;
    }

    /** Creates new form ManajemenPiutang */
    public ManajemenPiutang() {
        initComponents();
        listHutang = Main.getTransaksiService().hutangRecord(TransaksiStatus.U);
        tblPiutangData.setModel(new PiutangTableModel(listHutang));
    }

//    String getAbsolutePath() {
//        java.security.ProtectionDomain pd =
//                ReportServiceImpl.class.getProtectionDomain();
//        if (pd == null) {
//            return null;
//        }
//        java.security.CodeSource cs = pd.getCodeSource();
//        if (cs == null) {
//            return null;
//        }
//        java.net.URL url = cs.getLocation();
//        if (url == null) {
//            return null;
//        }
//        java.io.File f = new File(url.getFile());
//        if (f == null) {
//            return null;
//        }
//        System.out.println("path =" + f.getAbsolutePath());
//        return f.getParentFile().getPath();
//    }
    private void aksiCetak(setoran st) {
    }

    private void aksiInfoPembayaran(setoran st) {
        JasperPrint getReport = Main.getReportService().getKartuPembayaranReport(st.getDetail().get(0).getKemudi().getKend().getNoLambung(), new DateTime(Main.getSistemService().sistemRecord().getTglKerja().getTime()).dayOfMonth().withMinimumValue().toDate(), new DateTime(Main.getSistemService().sistemRecord().getTglKerja().getTime()).dayOfMonth().withMaximumValue().toDate(), isClosedFor.CLOSING_SALDO_BULAN_LALU, new DateTime(Main.getSistemService().sistemRecord().getTglKerja()).minusMonths(1).getMonthOfYear());
        JasperViewer.viewReport(getReport, false);
    }

    private void aksiInfoLambung(setoran st) {
        JasperPrint getReport = Main.getReportService().getDataLambungForPiutangReport(st.getDetail().get(0).getKemudi().getKend().getNoLambung(), Main.getTransaksiService().setoranRecord().get(0).getTglSPO(), Main.getSistemService().sistemRecord().getTglKerja());
        JasperViewer.viewReport(getReport, false);
    }

    private void aksiCatatan(setoran st) {
        new createNotesDialog().showDialog(st.getDetail().get(0).getKemudi().getKend().getNoLambung());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblMenuContext = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPiutangData = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Manajemen Piutang - Armada Biru");

        jLabel1.setText("No. Lambung");

        jLabel2.setText("NRP");

        jLabel3.setText("Nama");

        jLabel4.setText("Tgl Setoran");

        tblPiutangData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Lambung", "  NRP", "  Nama", "  Total Setoran", "  Total Hutang", " Set.Ke", "  Tgl Jatuh Tempo", "  Tgl SPO"
            }
        ));
        tblPiutangData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPiutangDataMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblPiutangDataMouseReleased(evt);
            }
        });
        tblPiutangData.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblPiutangDataMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(tblPiutangData);
        tblPiutangData.getColumnModel().getColumn(0).setMinWidth(80);
        tblPiutangData.getColumnModel().getColumn(0).setMaxWidth(80);

        jPanel4.setBackground(new java.awt.Color(0, 73, 255));

        jLabel12.setFont(new java.awt.Font("BPG Chveulebrivi", 1, 13));
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("  Manajemen Piutang");

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnRefresh.setText("Muat Ulang");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 810, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(btnRefresh))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int previousClick = -1;
    private void tblPiutangDataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPiutangDataMouseReleased
        // TODO add your handling code here:
        if (OsUtils.isWindows()) {
            if (evt.isPopupTrigger()) {
                tblPiutangData = (JTable) evt.getSource();
                int row = tblPiutangData.rowAtPoint(evt.getPoint());
                int column = tblPiutangData.columnAtPoint(evt.getPoint());

                if (!tblPiutangData.isRowSelected(row)) {
                    tblPiutangData.changeSelection(row, column, false, false);
                }
                sto = listHutang.get(tblPiutangData.getSelectedRow());
                JMenuItem mnuCetak = new JMenuItem("Cetak Printer");
                JMenuItem mnuPembayaran = new JMenuItem("Lihat Kartu Pembayaran");
                JMenuItem mnuInfoLambung = new JMenuItem("Lihat Informasi Data Lambung");
                JMenuItem mnuCatatan = new JMenuItem("Buat Catatan");

                mnuCetak.addActionListener(new java.awt.event.ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        aksiCetak(sto);
                    }
                });
                mnuPembayaran.addActionListener(new java.awt.event.ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        aksiInfoPembayaran(sto);
                    }
                });
                mnuInfoLambung.addActionListener(new java.awt.event.ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        aksiInfoLambung(sto);
                    }
                });
                mnuCatatan.addActionListener(new java.awt.event.ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        aksiCatatan(sto);
                    }
                });

                JPanel pnlTitle = new JPanel();
                pnlTitle.setBackground(new java.awt.Color(0, 73, 255));
                pnlTitle.setSize(150, 40);
                pnlTitle.setLayout(new java.awt.FlowLayout(FlowLayout.CENTER));
                JLabel title = new JLabel("Menu Lambung " + sto.getDetail().get(0).getKemudi().getKend().getNoLambung().toString());
                title.setFont(new java.awt.Font("BPG Chveulebrivi", 1, 13));
                title.setForeground(new java.awt.Color(254, 254, 254));
                pnlTitle.add(title, BorderLayout.EAST);
                popupMenuContext = new JPopupMenu("Menu Context");
                popupMenuContext.add(pnlTitle);
                popupMenuContext.add(mnuCetak);
                popupMenuContext.add(mnuPembayaran);
                popupMenuContext.add(mnuInfoLambung);
                popupMenuContext.add(mnuCatatan);
                popupMenuContext.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tblPiutangDataMouseReleased

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        listHutang = Main.getTransaksiService().hutangRecord(TransaksiStatus.U);
        tblPiutangData.removeAll();
        tblPiutangData.setModel(new PiutangTableModel(listHutang));
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblPiutangDataMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPiutangDataMouseMoved
        // TODO add your handling code here:
        Point pt = new Point(evt.getPoint());
        int row = tblPiutangData.rowAtPoint(pt);
        int col = tblPiutangData.columnAtPoint(pt);
        if (tblPiutangData.getSelectedRow() > -1) {
            sto = listHutang.get(tblPiutangData.getSelectedRow());
            tblPiutangData.setToolTipText(sto.getDetail().get(0).getKet());
            tblPiutangData.getToolTipLocation(evt);
        }
    }//GEN-LAST:event_tblPiutangDataMouseMoved

    private void tblPiutangDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPiutangDataMousePressed
        // TODO add your handling code here:
        if (OsUtils.isUnix()) {
            if (evt.isPopupTrigger()) {
                tblPiutangData = (JTable) evt.getSource();
                int row = tblPiutangData.rowAtPoint(evt.getPoint());
                int column = tblPiutangData.columnAtPoint(evt.getPoint());

                if (!tblPiutangData.isRowSelected(row)) {
                    tblPiutangData.changeSelection(row, column, false, false);
                }
                sto = listHutang.get(tblPiutangData.getSelectedRow());
                JMenuItem mnuCetak = new JMenuItem("Cetak Printer");
                JMenuItem mnuPembayaran = new JMenuItem("Lihat Kartu Pembayaran");
                JMenuItem mnuInfoLambung = new JMenuItem("Lihat Informasi Data Lambung");
                JMenuItem mnuCatatan = new JMenuItem("Buat Catatan");

                mnuCetak.addActionListener(new java.awt.event.ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        aksiCetak(sto);
                    }
                });
                mnuPembayaran.addActionListener(new java.awt.event.ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        aksiInfoPembayaran(sto);
                    }
                });
                mnuInfoLambung.addActionListener(new java.awt.event.ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        aksiInfoLambung(sto);
                    }
                });
                mnuCatatan.addActionListener(new java.awt.event.ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        aksiCatatan(sto);
                    }
                });

                JPanel pnlTitle = new JPanel();
                pnlTitle.setBackground(new java.awt.Color(0, 73, 255));
                pnlTitle.setSize(150, 40);
                pnlTitle.setLayout(new java.awt.FlowLayout(FlowLayout.CENTER));
                JLabel title = new JLabel("Menu Lambung " + sto.getDetail().get(0).getKemudi().getKend().getNoLambung().toString());
                title.setFont(new java.awt.Font("BPG Chveulebrivi", 1, 13));
                title.setForeground(new java.awt.Color(254, 254, 254));
                pnlTitle.add(title, BorderLayout.EAST);
                popupMenuContext = new JPopupMenu("Menu Context");
                popupMenuContext.add(pnlTitle);
                popupMenuContext.add(mnuCetak);
                popupMenuContext.add(mnuPembayaran);
                popupMenuContext.add(mnuInfoLambung);
                popupMenuContext.add(mnuCatatan);
                popupMenuContext.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tblPiutangDataMousePressed

    @Override
    public Point getToolTipLocation(MouseEvent event) {
        Point p = new Point(event.getX(), event.getY());
        return p;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPopupMenu tblMenuContext;
    private javax.swing.JTable tblPiutangData;
    // End of variables declaration//GEN-END:variables
}
