/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * createNotesDialog.java
 *
 * Created on 05 Sep 12, 20:35:43
 */
package paperman.dialog;

import java.util.List;
import javax.swing.JOptionPane;
import paperman.Main;
import paperman.model.TransaksiStatus;
import paperman.model.setoran;
import paperman.model.setoranDetail;
import paperman.model.setoranDetailPutih;
import paperman.model.setoranPutih;

/**
 *
 * @author Nurul Chusna
 */
public class createNotesDialog extends javax.swing.JDialog {

    /** Creates new form createNotesDialog */
    private setoran st;
    private setoranPutih stPutih;
    private setoranDetail sd;
    private setoranDetailPutih stDetailPutih;
    private List<setoran> listSetoran;
    private List<setoranDetail> listSetoranDetail;
    private List<setoranDetailPutih> listSetoranDetailPutih;

    public createNotesDialog() {
        super(Main.getMainMenu(), true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public setoran showDialog(Integer lambung) {
        System.out.println("lambung= " + lambung);
        LoadData(lambung);
        this.setVisible(true);
        return st;
    }

    public setoranPutih showDialogPutih(Integer lambung) {
        System.out.println("lambung= " + lambung);
        LoadDataPutih(lambung);
        this.setVisible(true);
        return stPutih;
    }

    private void LoadData(Integer noLambung) {
        st = Main.getTransaksiService().findHutangByNoLambung(noLambung, TransaksiStatus.U);
        if (st.getId() != null) {
            txtCatatan.setText(st.getDetail().get(0).getKet());
        }
    }

    private void LoadDataPutih(Integer noLambung) {
        stPutih = Main.getTransaksiService().findHutangPutihByNoLambung(noLambung, TransaksiStatus.U);
        if (stPutih.getId() != null) {
            txtCatatan.setText(stPutih.getDetailPutih().get(0).getKet());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCatatan = new javax.swing.JTextArea();
        btnTerbit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 73, 255));

        lblTitle.setFont(new java.awt.Font("BPG Chveulebrivi", 1, 13));
        lblTitle.setForeground(new java.awt.Color(254, 254, 254));
        lblTitle.setText(" Buat Catatan No.LB");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText(" Buat Catatan :");

        txtCatatan.setColumns(20);
        txtCatatan.setRows(5);
        jScrollPane1.setViewportView(txtCatatan);

        btnTerbit.setText("Terbitkan");
        btnTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerbitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerbitActionPerformed
        // TODO add your handling code here:
        if (st != null) {
            st.getDetail().get(0).setKet(txtCatatan.getText());
            Main.getTransaksiService().save(st);
            txtCatatan.setText("");
            JOptionPane.showMessageDialog(this, "Catatan Telah Di Buat, Sorot Tabel Menggunakan Mouse Untuk Melihat", "Pesan Sistem", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            System.gc();
        } else if (stPutih != null) {
            stPutih.getDetailPutih().get(0).setKet(txtCatatan.getText());
            Main.getTransaksiService().save(stPutih);
            txtCatatan.setText("");
            JOptionPane.showMessageDialog(this, "Catatan Telah Di Buat, Sorot Tabel Menggunakan Mouse Untuk Melihat", "Pesan Sistem", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            System.gc();
        }
    }//GEN-LAST:event_btnTerbitActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTerbit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtCatatan;
    // End of variables declaration//GEN-END:variables
}
