/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LookupReffNoLambung.java
 *
 * Created on Jun 11, 2012, 7:42:29 AM
 */
package paperman.dialog;

import java.util.ArrayList;
import java.util.List;
import paperman.Main;
import paperman.model.kendaraan;
import paperman.model.setoranDetail;
import paperman.tablemodel.LookupReffNoLambungTableModel;

/**
 *
 * @author i1440ns
 */
public class LookupReffNoLambung extends javax.swing.JDialog {

    private List<setoranDetail> listSetoranDet = new ArrayList<setoranDetail>();
    private setoranDetail stoDet;

    /** Creates new form LookupReffNoLambung */
    public LookupReffNoLambung() {
        super(Main.getMainMenu(), true);
        initComponents();
        this.setLocationRelativeTo(null);
        tblReff.setAutoCreateColumnsFromModel(false);
    }

    public setoranDetail showDialog() {
        LoadDataToTable();
        this.setVisible(true);
        return stoDet;
    }

    private void LoadDataToTable() {
        listSetoranDet = Main.getTransaksiService().setoranDetailRecord();
        tblReff.setModel(new LookupReffNoLambungTableModel(listSetoranDet));
        initColumn();
    }

    private void initColumn() {
        tblReff.getColumnModel().getColumn(0).setMinWidth(250);
        tblReff.getColumnModel().getColumn(0).setMaxWidth(250);
        tblReff.getColumnModel().getColumn(1).setMinWidth(250);
        tblReff.getColumnModel().getColumn(1).setMaxWidth(250);
        tblReff.getColumnModel().getColumn(2).setMinWidth(250);
        tblReff.getColumnModel().getColumn(2).setMaxWidth(250);
        tblReff.getColumnModel().getColumn(3).setMinWidth(250);
        tblReff.getColumnModel().getColumn(3).setMaxWidth(250);
        tblReff.getColumnModel().getColumn(4).setMinWidth(250);
        tblReff.getColumnModel().getColumn(4).setMaxWidth(250);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReff = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Cari No Lambung");

        tblReff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "  No. Lambung", "  NRP", "  Nama", "  Tgl. Jatuh Tempo", "  Keterangan"
            }
        ));
        tblReff.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblReff.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblReff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReff);
        tblReff.getColumnModel().getColumn(0).setMinWidth(250);
        tblReff.getColumnModel().getColumn(0).setMaxWidth(250);
        tblReff.getColumnModel().getColumn(1).setMinWidth(250);
        tblReff.getColumnModel().getColumn(1).setMaxWidth(250);
        tblReff.getColumnModel().getColumn(2).setMinWidth(250);
        tblReff.getColumnModel().getColumn(2).setMaxWidth(250);
        tblReff.getColumnModel().getColumn(3).setMinWidth(250);
        tblReff.getColumnModel().getColumn(3).setMaxWidth(250);
        tblReff.getColumnModel().getColumn(4).setMinWidth(250);
        tblReff.getColumnModel().getColumn(4).setMaxWidth(250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int previousClick = -1;
    private void tblReffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReffMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 || evt.getClickCount() == 1 && previousClick == tblReff.getSelectedRow()) {
            stoDet = listSetoranDet.get(tblReff.getSelectedRow());
            this.dispose();
        }else {
            previousClick = tblReff.getSelectedRow();
        }
    }//GEN-LAST:event_tblReffMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        tblReff.getSelectionModel().clearSelection();
        stoDet = null;
    }//GEN-LAST:event_formWindowClosing
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReff;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
