/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LookupTambahSetoran.java
 *
 * Created on 17 Okt 12, 14:28:50
 */
package paperman.dialog;

import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import paperman.Main;
import paperman.TextComponentUtils;
import paperman.config.Sistem;
import paperman.model.komposisiSetoran;

/**
 *
 * @author Nurul Chusna
 */
public class LookupTambahKomposisiSetoran extends javax.swing.JDialog {

    /** Creates new form LookupTambahSetoran */
    private static LookupTambahKomposisiSetoran lookupTambahKomposisi;
    private komposisiSetoran komposisi;
    private List<komposisiSetoran> listKomposisi = new ArrayList<komposisiSetoran>();
    private static Sistem sys;

    public LookupTambahKomposisiSetoran() {
        super(Main.getMainMenu(), true);
        initComponents();
        this.setLocationRelativeTo(null);
        TextComponentUtils.setCurrency(txtAngsuran);
        TextComponentUtils.setCurrency(txtTabungan);
    }

    public komposisiSetoran showDialog() {
        this.setVisible(true);
        return komposisi;
    }

    public komposisiSetoran showDialog(komposisiSetoran ks) {
        this.komposisi = ks;
        txtNamaKomposisi.setText(komposisi.getNamaKomposisi());
        txtAngsuran.setText(TextComponentUtils.formatNumber(komposisi.getAngsuran()));
        txtTabungan.setText(TextComponentUtils.formatNumber(komposisi.getTabungan()));
        if (komposisi.getStatus().compareTo(Boolean.TRUE) == 0) {
            cbDefault.setSelected(true);
        } else {
            cbDefault.setSelected(false);
        }
        listKomposisi.add(ks);
        this.setVisible(true);
        return komposisi;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAngsuran = new javax.swing.JTextField();
        txtTabungan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNamaKomposisi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbDefault = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tambah Komposisi Setoran");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Nilai Angsuran");

        jLabel3.setText("Nilai Tabungan");

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnTambah.setText("Tambah / Update");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Komposisi");

        jLabel5.setText("Set Default");

        cbDefault.setText("Tidak");
        cbDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDefault)
                    .addComponent(txtNamaKomposisi, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAngsuran, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(txtTabungan, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAngsuran, txtNamaKomposisi, txtTabungan});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatal, btnTambah});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNamaKomposisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAngsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTabungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbDefault))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBatal, btnTambah});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if (komposisi == null) {
            komposisi = new komposisiSetoran();
        }
        if (!txtNamaKomposisi.getText().isEmpty() && !txtAngsuran.getText().isEmpty() && !txtTabungan.getText().isEmpty()) {
            if (Sistem.isEditOrDeleteFire) {
                komposisi.setId(listKomposisi.get(0).getId());
            }
            komposisi.setNamaKomposisi(txtNamaKomposisi.getText());
            komposisi.setAngsuran(TextComponentUtils.parseNumberToBigDecimal(txtAngsuran.getText()));
            komposisi.setTabungan(TextComponentUtils.parseNumberToBigDecimal(txtTabungan.getText()));
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Tambah Komposisi Gagal\nPeriksa Lagi", "Pesan Sistem", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        komposisi = null;
        System.gc();
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void cbDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDefaultActionPerformed
        // TODO add your handling code here:
        komposisi = new komposisiSetoran();
        if (cbDefault.isSelected()) {
            cbDefault.setFont(new Font("BPG Chveulebrivi", Font.BOLD, 13));
            cbDefault.setText("Ya");
            komposisi.setStatus(true);
        } else {
            cbDefault.setFont(new Font("BPG Chveulebrivi", Font.PLAIN, 13));
            cbDefault.setText("Tidak");
            komposisi.setStatus(false);
        }
    }//GEN-LAST:event_cbDefaultActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnTambah;
    private javax.swing.JCheckBox cbDefault;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAngsuran;
    private javax.swing.JTextField txtNamaKomposisi;
    private javax.swing.JTextField txtTabungan;
    // End of variables declaration//GEN-END:variables
}
