/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpenClosedTrans.java
 *
 * Created on Jun 20, 2013, 4:08:06 PM
 */

package paperman.dialog;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.joda.time.DateTime;
import paperman.Main;
import paperman.model.isClosedStatus;
import paperman.model.setoran;
import paperman.model.setoranDetail;

/**
 *
 * @author supervisor
 */
public class OpenClosedTrans extends javax.swing.JDialog {

    /** Creates new form OpenClosedTrans */
    private List<setoranDetail> listSetoranDetail = new ArrayList<setoranDetail>();
    public static boolean isUpdatingClosing = false;
    public static Date lastClosing;
    public static String lastSelectedTagArmada = "";

    public OpenClosedTrans() {
        super(Main.getMainMenu(), true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public List<setoranDetail> showDialog() {
        this.setVisible(true);
        return listSetoranDetail;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBatal = new javax.swing.JButton();
        cmbJenisArmada = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        mTitlePanel1 = new id.web.martinusadyh.panel.MTitlePanel();
        bulanClosing = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pembukaan Ulang Closed Transaksi");

        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        cmbJenisArmada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BIRU", "NEW BIRU" }));

        jLabel2.setText("Jenis Armada");

        btnProses.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnProses.setText("PROSES");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        mTitlePanel1.setBorder(null);
        mTitlePanel1.setFontTitle(new java.awt.Font("Tahoma", 1, 14));
        mTitlePanel1.setIconHelpVisible(false);
        mTitlePanel1.setTextTitlePanel("Buka Closed Transaksi");

        bulanClosing.setDateFormatString("MMMM yyyy");

        jLabel1.setText("Periode Bulan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mTitlePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bulanClosing, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(cmbJenisArmada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBatal, btnProses});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mTitlePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbJenisArmada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bulanClosing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProses, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        listSetoranDetail = null;
        isUpdatingClosing = false;
        this.dispose();
}//GEN-LAST:event_btnBatalActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        if (bulanClosing.getDate() != null) {
            listSetoranDetail = Main.getTransaksiService().findAvailableSetoran(isClosedStatus.CLOSED, bulanClosing.getDate(), bulanClosing.getDate(), cmbJenisArmada.getSelectedItem().toString());
            for(int i=0;i<listSetoranDetail.size();i++) {
                listSetoranDetail.get(i).getSetor_map().setClosedStatus(isClosedStatus.AVAILABLE);
                listSetoranDetail.get(i).getSetor_map().setIdClosing(null);
                setoran st = listSetoranDetail.get(i).getSetor_map();
                Main.getTransaksiService().save(st);
            }
            isUpdatingClosing = true;
            lastClosing = bulanClosing.getDate();
            lastSelectedTagArmada = cmbJenisArmada.getSelectedItem().toString();
            JOptionPane.showMessageDialog(this, "Transaksi Setoran " + cmbJenisArmada.getSelectedItem().toString() + " Closing Bulan " + new DateTime(bulanClosing.getDate()).monthOfYear().getAsText() + " Telah Dilakukan Oleh 'Set User'", "Pesan Sistem", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Harap Isi Periode Bulan", "Pesan Sistem", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
}//GEN-LAST:event_btnProsesActionPerformed

    /**
    * @param args the command line arguments
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnProses;
    private com.toedter.calendar.JDateChooser bulanClosing;
    private javax.swing.JComboBox cmbJenisArmada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private id.web.martinusadyh.panel.MTitlePanel mTitlePanel1;
    // End of variables declaration//GEN-END:variables

}
