/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PilihKomposisi.java
 *
 * Created on 17 Okt 12, 15:14:28
 */
package paperman.dialog;

import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import paperman.Main;
import paperman.model.komposisiSetoran;
import paperman.tablemodel.PilihKomposisiSetoranTableModel;

/**
 *
 * @author Nurul Chusna
 */
public class PilihKomposisi extends javax.swing.JDialog implements ListSelectionListener {

    /** Creates new form PilihKomposisi */
    private komposisiSetoran komposisi;
    private List<komposisiSetoran> listKomposisi;

    public PilihKomposisi() {
        super(Main.getMainMenu(), true);
        initComponents();
        setLocationRelativeTo(null);
        LoadDataToTable();
        tblKomposisi.getSelectionModel().addListSelectionListener(this);
        tblKomposisi.setAutoCreateColumnsFromModel(false);
    }

    public komposisiSetoran showDialog() {
        LoadDataToTable();
        this.setVisible(true);
        return komposisi;
    }

    public komposisiSetoran showDialogDataBonus() {
        LoadDataBonusToTable();
        this.setVisible(true);
        return komposisi;
    }

    public komposisiSetoran showDialogDataBonusPutih() {
        LoadDataBonusPutihToTable();
        this.setVisible(true);
        return komposisi;
    }

    private void LoadDataToTable() {
        listKomposisi = Main.getSistemService().komposisiRecord();
        tblKomposisi.setModel(new PilihKomposisiSetoranTableModel(listKomposisi));
        initColumnSize();
    }

    private void LoadDataBonusToTable() {
        listKomposisi = Main.getSistemService().findBonusBulanan();
        tblKomposisi.setModel(new PilihKomposisiSetoranTableModel(listKomposisi));
        initColumnSize();
    }

    private void LoadDataBonusPutihToTable() {
        komposisi = Main.getSistemService().findBonusBulananPutih();
        listKomposisi.add(komposisi);
        tblKomposisi.setModel(new PilihKomposisiSetoranTableModel(listKomposisi));
        initColumnSize();
    }

    private void initColumnSize() {
        tblKomposisi.getColumnModel().getColumn(0).setMinWidth(150);
        tblKomposisi.getColumnModel().getColumn(0).setMaxWidth(200);
        tblKomposisi.getColumnModel().getColumn(1).setMinWidth(150);
        tblKomposisi.getColumnModel().getColumn(1).setMaxWidth(200);
        tblKomposisi.getColumnModel().getColumn(2).setMinWidth(150);
        tblKomposisi.getColumnModel().getColumn(2).setMaxWidth(200);
    }

    public void valueChanged(ListSelectionEvent e) {
        if (tblKomposisi.getSelectedRow() >= 0) {
            komposisi = listKomposisi.get(tblKomposisi.getSelectedRow());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKomposisi = new javax.swing.JTable();
        cbSetDefault = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesan Sistem");

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilih Jenis Komposisi Yang Akan Di Muat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblKomposisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblKomposisi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKomposisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKomposisiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKomposisi);

        cbSetDefault.setText("Selalu Ingat Pilihan Ini");
        cbSetDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSetDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbSetDefault)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSetDefault)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKomposisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKomposisiMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            komposisi = new komposisiSetoran();
            komposisi = listKomposisi.get(tblKomposisi.getSelectedRow());
            this.dispose();
        }
    }//GEN-LAST:event_tblKomposisiMouseClicked

    private void cbSetDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSetDefaultActionPerformed
        // TODO add your handling code here:
        if (cbSetDefault.isSelected()) {
            cbSetDefault.setFont(new Font("BPG Chveulebrivi", Font.BOLD, 13));
            cbSetDefault.setText("Selalu Ingat Pilihan Ini");
            int pil = JOptionPane.showConfirmDialog(this, "Anda Yakin Akan Menjadikan Komposisi " + komposisi.getNamaKomposisi() + "Sebagai Default ?", "Pesan Sistem", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (pil == JOptionPane.YES_OPTION) {
                komposisi.setStatus(true);
                Main.getSistemService().save(komposisi);
                this.dispose();
            }
            if (pil == JOptionPane.NO_OPTION) {
                cbSetDefault.setSelected(false);
                cbSetDefault.setFont(new Font("BPG Chveulebrivi", Font.PLAIN, 13));
                cbSetDefault.setText("Selalu Ingat Pilihan Ini");
                return;
            }
        } 
    }//GEN-LAST:event_cbSetDefaultActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbSetDefault;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKomposisi;
    // End of variables declaration//GEN-END:variables
}
