/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pnlPiutangMenuContext.java
 *
 * Created on 01 Sep 12, 7:27:36
 */
package paperman.dialog;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.util.ArrayList;
import java.util.List;
import paperman.Main;
import paperman.model.setoran;
import paperman.model.setoranDetail;
import paperman.transaksi.ManajemenPiutang;

/**
 *
 * @author Nurul Chusna
 */
public class pnlPiutangMenuContext extends javax.swing.JPanel{

    /** Creates new form pnlPiutangMenuContext */
    private setoran s;
    private setoranDetail sd;

    public pnlPiutangMenuContext() {
        initComponents();
    }

    public setoran showDialog(setoran st) {
        LoadData(st);
        this.setVisible(true);
        return s;
    }

    private void LoadData(setoran sto) {
//        for (int i = 0; i <= sto.getDetail().size(); i++) {
//        if (sd == null) {
//            sd = new setoranDetail();
//        }
//        sd.setSetor_map(sto);
        lblTitle.setText("Menu Lambung " + sto.getDetail().get(0).getKemudi().getKend().getNoLambung().toString());
//        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setOpaque(false);

        jLabel1.setText("   Cetak Printer");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setText("   Lihat Kartu Pembayaran");

        jLabel3.setText("   Lihat Informasi Data Lambung");

        jLabel4.setText("   Buat Catatan");

        jPanel4.setBackground(new java.awt.Color(0, 73, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("BPG Chveulebrivi", 1, 13));
        lblTitle.setForeground(new java.awt.Color(254, 254, 254));
        lblTitle.setText("  Menu Lambung");
        jPanel4.add(lblTitle, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
